### This file is generated by opam2nix.
self: let
  lib = self.lib;
  pkgs = self.pkgs;
  selection = self.selection;
  repoPath = self.repoPath;
  repos = {
    opam-repository = rec {
      fetch = {
        owner = "ocaml";
        repo = "opam-repository";
        rev = "5689da8bd56540a82673575b22c3c07795f3609d";
        sha256 = "04a0wjb7kdz7xk42p9gd7md3wpcxpz5b0w41m2gvr12kfvzvab7i";
      };
      src = (pkgs.fetchFromGitHub) fetch;
    };
  };
in {
  format-version = 4;
  inherit repos;
  ocaml-version = "4.12.0";
  selection = {
    alt-ergo = {
      pname = "alt-ergo";
      version = "2.4.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/OCamlPro/alt-ergo/archive/2.4.0.tar.gz";
          sha256 = "1b1vk7vaw0hqff9li27ngnsm1f8prvcq9v41q56gafacvqw1ii6h";
        };
      opamInputs = {
        inherit
          (selection)
          ocaml
          menhir
          dune
          cmdliner
          alt-ergo-parsers
          alt-ergo-lib
          ;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/alt-ergo/alt-ergo.2.4.0";
          hash = "sha256:05cqkbk8az4n20nvk5jysbfwkahfyh4w8gcs3v37cp7brkvv882n";
        };
    };
    alt-ergo-lib = {
      pname = "alt-ergo-lib";
      version = "2.4.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/OCamlPro/alt-ergo/archive/2.4.0.tar.gz";
          sha256 = "1b1vk7vaw0hqff9li27ngnsm1f8prvcq9v41q56gafacvqw1ii6h";
        };
      opamInputs = {
        inherit
          (selection)
          zarith
          stdlib-shims
          seq
          ocplib-simplex
          ocaml
          num
          dune-configurator
          dune
          ;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/alt-ergo-lib/alt-ergo-lib.2.4.0";
          hash = "sha256:1v35qrip8bcwin3kysikpinyksc9dx5pi2fp9w8iqnyg2lxcr7h2";
        };
    };
    alt-ergo-parsers = {
      pname = "alt-ergo-parsers";
      version = "2.4.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/OCamlPro/alt-ergo/archive/2.4.0.tar.gz";
          sha256 = "1b1vk7vaw0hqff9li27ngnsm1f8prvcq9v41q56gafacvqw1ii6h";
        };
      opamInputs = {
        inherit
          (selection)
          stdlib-shims
          psmt2-frontend
          ocaml
          menhir
          dune
          camlzip
          alt-ergo-lib
          ;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/alt-ergo-parsers/alt-ergo-parsers.2.4.0";
          hash = "sha256:15l3p4hscphff7kyirpicijs6bp6qvr4bp0fiav3ifg2aik2sshi";
        };
    };
    base-bytes = {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
        inherit (selection) ocamlfind ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/base-bytes/base-bytes.base";
          hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
        };
    };
    base-threads = {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/base-threads/base-threads.base";
          hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
        };
    };
    base-unix = {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/base-unix/base-unix.base";
          hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
        };
    };
    bindlib = {
      pname = "bindlib";
      version = "5.0.1";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/rlepigre/ocaml-bindlib/archive/ocaml-bindlib_5.0.1.tar.gz";
          sha256 = "0hdrd4qflfx8n0f31bgx8jbmjxx5v5cznx3nzqq0gh75bd943ir5";
        };
      opamInputs = {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/bindlib/bindlib.5.0.1";
          hash = "sha256:1ssv4fm6ymmqll7xk2cz22i03dbg303jml90mxjvr64qlp1mbwvx";
        };
    };
    biniou = {
      pname = "biniou";
      version = "1.2.1";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/mjambon/biniou/releases/download/1.2.1/biniou-1.2.1.tbz";
          sha256 = "0da3m0g0dhl02jfynrbysjh070xk2z6rxcx34xnqx6ljn5l6qm1m";
        };
      opamInputs = {
        inherit (selection) ocaml easy-format dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/biniou/biniou.1.2.1";
          hash = "sha256:1m9s9v4zr7022k6d50482qq7w41fdqp58nkpfhcp8574hg65kh69";
        };
    };
    camlzip = {
      pname = "camlzip";
      version = "1.11";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/xavierleroy/camlzip/archive/rel111.tar.gz";
          sha256 = "0dzdspqp9nzx8wyhclbm68dykvfj6b97c8r7b47dq4qw7vgcbfzz";
        };
      opamInputs = {
        inherit (selection) ocamlfind ocaml conf-zlib;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/camlzip/camlzip.1.11";
          hash = "sha256:03mx2dfl1y883jkcdyjpnk6larv2m6gwkg17fr77rwx0xz546c2x";
        };
    };
    cmdliner = {
      pname = "cmdliner";
      version = "1.0.4";
      src =
        pkgs.fetchurl
        {
          url = "http://erratique.ch/software/cmdliner/releases/cmdliner-1.0.4.tbz";
          sha256 = "1h04q0zkasd0mw64ggh4y58lgzkhg6yhzy60lab8k8zq9ba96ajw";
        };
      opamInputs = {
        inherit (selection) ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/cmdliner/cmdliner.1.0.4";
          hash = "sha256:05qlm4yp6124w2z10dpdchldfrmgmcr6h31rnxp8qs8mk0xzx48z";
        };
    };
    conf-autoconf = {
      pname = "conf-autoconf";
      version = "0.1";
      src = null;
      opamInputs = {
        inherit (selection) conf-which;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/conf-autoconf/conf-autoconf.0.1";
          hash = "sha256:1y7kgxjf1pdh8hpjai2vg1n1r7zl5349i4sq1g509kdr72l5xhvn";
        };
      buildInputs = [(pkgs.autoconf)];
    };
    conf-gmp = {
      pname = "conf-gmp";
      version = "4";
      src = null;
      opamInputs = {
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/conf-gmp/conf-gmp.4";
          hash = "sha256:0haqsxx298i2c4qb9nqqq0nwh4xpcd7h54l78kn4gmyrc8dmajpw";
        };
      buildInputs = [
        (pkgs.gmp or null)
        (pkgs.gmp-dev or null)
        (pkgs.gmp-devel or null)
        (pkgs.libgmp-dev or null)
        (pkgs.mingw64-x86_64-gmp or null)
      ];
    };
    conf-pkg-config = {
      pname = "conf-pkg-config";
      version = "2";
      src = null;
      opamInputs = {
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/conf-pkg-config/conf-pkg-config.2";
          hash = "sha256:1rli6809glz5g9xwp4wsjidc39za4n58xcpkamy6fymfnqha225n";
        };
      buildInputs = [(pkgs.pkgconfig)];
    };
    conf-which = {
      pname = "conf-which";
      version = "1";
      src = null;
      opamInputs = {
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/conf-which/conf-which.1";
          hash = "sha256:1nsp1qv5j3r6pw6qgmrlpdbcz8l6mjg2kgmdiv4nhxv0wm8psg44";
        };
      buildInputs = [(pkgs.which)];
    };
    conf-zlib = {
      pname = "conf-zlib";
      version = "1";
      src = null;
      opamInputs = {
        inherit (selection) conf-pkg-config;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/conf-zlib/conf-zlib.1";
          hash = "sha256:159cs38ympzqq8dwaz4friwq7il6mgcvns5snkiax3zn03fjwk7l";
        };
      buildInputs = [(pkgs.zlib)];
    };
    cppo = {
      pname = "cppo";
      version = "1.6.8";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml-community/cppo/archive/v1.6.8.tar.gz";
          sha256 = "0lxy4xkkkwgs1cj6d9lyzsqi9f6fc9r6cir5imi7yjqrpd86s1by";
        };
      opamInputs = {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/cppo/cppo.1.6.8";
          hash = "sha256:0pzd8irqkkkpfgw8nq9d21z9rj5m3qlzixyb7ybfy4b1fwh3n8bp";
        };
    };
    csexp = {
      pname = "csexp";
      version = "1.5.1";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.1/csexp-1.5.1.tbz";
          sha256 = "00mc19f89pxpmjl62862ya5kjcfrl8rjzvs00j05h2m9bw3f81fn";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/csexp/csexp.1.5.1";
          hash = "sha256:01lc95kz13gpki4xazyh6n20kv1g9inyb5myv240wl2n9v50z8fl";
        };
    };
    dune = {
      pname = "dune";
      version = "2.9.1";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/dune/releases/download/2.9.1/dune-2.9.1.tbz";
          sha256 = "09lzq04b642iy0ljp59p32lgk3q8iphjh8fkdp69q29l5frgwx5k";
        };
      opamInputs = {
        inherit
          (selection)
          base-unix
          base-threads
          ;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/dune/dune.2.9.1";
          hash = "sha256:09s6k6kiw081kdh96zhp8ccgf8niw0391brfjl7gva7fansfqaqd";
        };
    };
    dune-configurator = {
      pname = "dune-configurator";
      version = "2.9.1";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/dune/releases/download/2.9.1/dune-2.9.1.tbz";
          sha256 = "09lzq04b642iy0ljp59p32lgk3q8iphjh8fkdp69q29l5frgwx5k";
        };
      opamInputs = {
        inherit (selection) result ocaml dune csexp;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/dune-configurator/dune-configurator.2.9.1";
          hash = "sha256:1aik9w82r8vbb9fsfphpb0vam68s19ggkxprnqr99ygyalp2b71j";
        };
    };
    easy-format = {
      pname = "easy-format";
      version = "1.3.2";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/mjambon/easy-format/releases/download/1.3.2/easy-format-1.3.2.tbz";
          sha256 = "09hrikx310pac2sb6jzaa7k6fmiznnmhdsqij1gawdymhawc4h1l";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/easy-format/easy-format.1.3.2";
          hash = "sha256:0rjgw1ygf8khwb7vgl5vnw907m8b5mpkb0bnlqiqz9zfmfb4jd47";
        };
    };
    gen = {
      pname = "gen";
      version = "0.5.3";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/c-cube/gen/archive/0.5.3.tar.gz";
          sha256 = "1jylp0i6952lj3cvmy2c4a5my5cbf39kynxgbh4xg3k7dp7540qn";
        };
      opamInputs = {
        inherit (selection) ocaml dune-configurator dune base-bytes;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/gen/gen.0.5.3";
          hash = "sha256:0h62m8pf7jdvl6acdw3pnmb9j37z0ph3acsm752kn6xvznijssd6";
        };
    };
    lambdapi = {
      pname = "lambdapi";
      version = "development";
      src = self.directSrc "lambdapi";
      opamInputs = {
        inherit
          (selection)
          yojson
          why3
          timed
          stdlib-shims
          sedlex
          pratter
          ocaml
          menhir
          dune
          cmdliner
          bindlib
          alt-ergo
          ;
      };
      opamSrc = "lambdapi.opam";
    };
    menhir = {
      pname = "menhir";
      version = "20211128";
      src =
        pkgs.fetchurl
        {
          url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
          sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
        };
      opamInputs = {
        inherit (selection) ocaml menhirSdk menhirLib dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/menhir/menhir.20211128";
          hash = "sha256:008frbinlbbv8ax0p3mzzwag7hlnpphng48va4mvjsmv8kdlll18";
        };
    };
    menhirLib = {
      pname = "menhirLib";
      version = "20211128";
      src =
        pkgs.fetchurl
        {
          url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
          sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/menhirLib/menhirLib.20211128";
          hash = "sha256:0qh7q4p9bwzaxi1fqa2wqwm3zgq90894rw68z7l222lmi1r79hky";
        };
    };
    menhirSdk = {
      pname = "menhirSdk";
      version = "20211128";
      src =
        pkgs.fetchurl
        {
          url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
          sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/menhirSdk/menhirSdk.20211128";
          hash = "sha256:0lmwvn6drhak1fwiphcsynsavwxahgq1447qj8jy2l23lccni7g7";
        };
    };
    num = {
      pname = "num";
      version = "1.4";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
          sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
        };
      opamInputs = {
        inherit (selection) ocamlfind ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/num/num.1.4";
          hash = "sha256:04wb8ww165lsifn36jcrxw5zs87id5kib6rilq6zh6qhzvij88pf";
        };
    };
    ocaml = {
      pname = "ocaml";
      version = "4.12.0";
      src = null;
      opamInputs = {
        inherit
          (selection)
          ocaml-config
          ;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocaml/ocaml.4.12.0";
          hash = "sha256:11mxrkiixqfyv0arpx57xk9kfa1an749lnbx6saf4h616llb5sj9";
        };
    };
    ocaml-base-compiler = {
      pname = "ocaml-base-compiler";
      version = "4.12.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/ocaml/archive/4.12.0.tar.gz";
          sha256 = "0i37laikik5vwydw1cwygxd8xq2d6n35l20irgrh691njlwpmh5d";
        };
      opamInputs = {
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.12.0";
          hash = "sha256:12clsv2kmwsfy685kjkjsyv41krfrr04ccpc11xhv6ar0090bsh5";
        };
    };
    ocaml-compiler-libs = {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
          sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
          hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
        };
    };
    ocaml-config = {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocaml-config/ocaml-config.2";
          hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
        };
    };
    ocamlbuild = {
      pname = "ocamlbuild";
      version = "0.14.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/ocamlbuild/archive/0.14.0.tar.gz";
          sha256 = "0y1fskw9rg2y1zgb7whv3v8v4xw04svgxslf3856q2aqd7lrrcl7";
        };
      opamInputs = {
        inherit (selection) ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocamlbuild/ocamlbuild.0.14.0";
          hash = "sha256:1r5qnrcxfypzyvjvb3zd9f66kr5ldxdl3g9rsi3pb6040krqb5w7";
        };
    };
    ocamlfind = {
      pname = "ocamlfind";
      version = "1.9.2";
      src =
        pkgs.fetchurl
        {
          url = "http://download.camlcity.org/download/findlib-1.9.2.tar.gz";
          sha256 = "0pjnn2z76zbsf07cj6k9fcvg62xvxqyxb9liq89nzxjgqy9a6zc6";
        };
      opamInputs = {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocamlfind/ocamlfind.1.9.2";
          hash = "sha256:1kswhqg79phvzi3p5fvasqgfm547xah14a0i9382y93562qficjm";
        };
    };
    ocplib-simplex = {
      pname = "ocplib-simplex";
      version = "0.4";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/OCamlPro-Iguernlala/ocplib-simplex/archive/v0.4.tar.gz";
          sha256 = "0y6q4bgly7fisdklriww48aknqf2vg4dphr7wwnd1wh80l4anzg1";
        };
      opamInputs = {
        inherit (selection) ocamlfind ocaml num conf-autoconf;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ocplib-simplex/ocplib-simplex.0.4";
          hash = "sha256:09hfij6ji24rjgrkf5qlp92if19dqm47lvp0fg3ql5p8pcxzh8c1";
        };
    };
    ppx_derivers = {
      pname = "ppx_derivers";
      version = "1.2.1";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
          sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ppx_derivers/ppx_derivers.1.2.1";
          hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
        };
    };
    ppxlib = {
      pname = "ppxlib";
      version = "0.24.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.24.0/ppxlib-0.24.0.tbz";
          sha256 = "1j4hg8gc8mkw64gvjghig1179ih90yki54hf8qxmn3yd5ry04rkp";
        };
      opamInputs = {
        inherit
          (selection)
          stdlib-shims
          sexplib0
          ppx_derivers
          ocaml-compiler-libs
          ocaml
          dune
          ;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/ppxlib/ppxlib.0.24.0";
          hash = "sha256:0yjsgdkfkbwyjj3yihrqnxlpagrbcr1gln7bxfmx96y3xa4fs8jv";
        };
    };
    pratter = {
      pname = "pratter";
      version = "1.2";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/gabrielhdt/pratter/releases/download/1.2/pratter-1.2.tbz";
          sha256 = "15x8mblhi1ggaby7i52408bsl4m45c1rg7d7jvjw87wv9j54frwp";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/pratter/pratter.1.2";
          hash = "sha256:13y41h5xd111hi2phh5jvp52jk3pm2bi1x436s1kns2ljqr56dxv";
        };
    };
    psmt2-frontend = {
      pname = "psmt2-frontend";
      version = "0.4.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/OCamlPro-Coquera/psmt2-frontend/archive/0.4.0.tar.gz";
          sha256 = "104pzq9kcsgaf2kns2766k1fh4j8wmclbyq89mq31ki9ns2givq6";
        };
      opamInputs = {
        inherit (selection) ocaml menhir dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/psmt2-frontend/psmt2-frontend.0.4.0";
          hash = "sha256:0i97dwwl7fzncwjrmw92jblfcdbakv56nc4g982lylj919d8xp2j";
        };
    };
    result = {
      pname = "result";
      version = "1.5";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
          sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/result/result.1.5";
          hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
        };
    };
    sedlex = {
      pname = "sedlex";
      version = "2.5";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml-community/sedlex/archive/v2.5.tar.gz";
          sha256 = "199ql06hpk3p2n1hbghl1iky8zwr7lzl8n4qf14pfp0lvgvdr62v";
        };
      opamInputs = {
        inherit (selection) uchar ppxlib ocaml gen dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/sedlex/sedlex.2.5";
          hash = "sha256:1nkp77i90jvdk67zcr53wgly6b2sa1300p3c14rhd4vlzwkms4vf";
        };
    };
    seq = {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
        inherit (selection) ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/seq/seq.base";
          hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
        };
    };
    sexplib0 = {
      pname = "sexplib0";
      version = "v0.14.0";
      src =
        pkgs.fetchurl
        {
          url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
          sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/sexplib0/sexplib0.v0.14.0";
          hash = "sha256:0k9vkjbiibja48c0yayal7xwyik3h3c3v4dwd3j7jbmras63ig2c";
        };
    };
    stdlib-shims = {
      pname = "stdlib-shims";
      version = "0.3.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
          sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
        };
      opamInputs = {
        inherit (selection) ocaml dune;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/stdlib-shims/stdlib-shims.0.3.0";
          hash = "sha256:19g9dnaxyh2ajz6pdczdsqzzvsmfrxwx6f613inkr31jw5hrqkiz";
        };
    };
    timed = {
      pname = "timed";
      version = "1.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/rlepigre/ocaml-timed/archive/ocaml-timed_1.0.tar.gz";
          sha256 = "1wygilmsrfnz2gwr58l0csq8d76hb0i149hxc6gcqcp0mhgrv9bi";
        };
      opamInputs = {
        inherit (selection) ocamlfind ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/timed/timed.1.0";
          hash = "sha256:1fwdmfgyca67vhn5fgm349skzn5q53g9f5h41sak7qlzc8wmc80x";
        };
    };
    uchar = {
      pname = "uchar";
      version = "0.0.2";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
          sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
        };
      opamInputs = {
        inherit (selection) ocamlbuild ocaml;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/uchar/uchar.0.0.2";
          hash = "sha256:17sfpyj5a1z3knnjvnfa5vql6cj2x9pzgzk8w4jrvd2zii2bwpcl";
        };
    };
    why3 = {
      pname = "why3";
      version = "1.4.0";
      src =
        pkgs.fetchurl
        {
          url = "https://why3.gitlabpages.inria.fr/releases/why3-1.4.0.tar.gz";
          sha256 = "0lw0cpx347zz9vvwqibmbxgs80fsd16scgk3isscvwxnajpc3rv8";
        };
      opamInputs = {
        inherit
          (selection)
          ocamlfind
          ocaml
          num
          menhir
          ;
        zarith = selection.zarith or null;
        sexplib = selection.sexplib or null;
        re = selection.re or null;
        ppx_sexp_conv = selection.ppx_sexp_conv or null;
        ocamlgraph = selection.ocamlgraph or null;
        camlzip = selection.camlzip or null;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/why3/why3.1.4.0";
          hash = "sha256:0f6ghm61pzvzc416n9cnmczd6xzxa89s3gikcfkqnbx4r5m2lch8";
        };
    };
    yojson = {
      pname = "yojson";
      version = "1.7.0";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml-community/yojson/releases/download/1.7.0/yojson-1.7.0.tbz";
          sha256 = "1iich6323npvvs8r50lkr4pxxqm9mf6w67cnid7jg1j1g5gwcvv5";
        };
      opamInputs = {
        inherit (selection) ocaml easy-format dune cppo biniou;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/yojson/yojson.1.7.0";
          hash = "sha256:1n8iih0jmaf9b0hsv6ph729jajws9w43kgm24324p4wlj45rjs2q";
        };
    };
    zarith = {
      pname = "zarith";
      version = "1.12";
      src =
        pkgs.fetchurl
        {
          url = "https://github.com/ocaml/Zarith/archive/release-1.12.tar.gz";
          sha256 = "1098xpqsq3gwpz9k2gc6ahiz2zk0z0xxi1lwc07nvj2570y5ccnc";
        };
      opamInputs = {
        inherit (selection) ocamlfind ocaml conf-gmp;
      };
      opamSrc =
        repoPath (repos.opam-repository.src)
        {
          package = "packages/zarith/zarith.1.12";
          hash = "sha256:03by05004bgfkfllpacf3vk1h8i6q7wzwi7cgxy0nyj5ffga0ggh";
        };
    };
  };
}
