
# Using directory stacks as directory history : zsh.sourceforge.net/Intro/intro_6.html
setopt autopushd pushdminus pushdsilent pushdtohome

# Change up/down keys behaviour : match commands in history by first letters
bindkey 'OA' history-beginning-search-backward
bindkey 'OB' history-beginning-search-forward

# reMarkable uploading
function reupload() {
	curl 'http://10.11.99.1/upload' -H 'Origin: http://10.11.99.1' -H 'Accept: */*' \
		-H 'Referrer: http://10.11.99.1/' -H 'Connection: keep-alive'           \
		-F "file=@$1;filename=$1;type=application/pdf"
}

# LS_COLORS setting
eval $(dircolors $XDG_CONFIG_HOME/zsh/dircolors)

# Print calendar
remind -w$(stty size | cut -d" " -f2) -b1 -cau+ ~/.local/share/remind/reminders

