# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ tree, stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "fzf-bibtex-unstable-${version}";
  version = "2019-12-12";
  rev = "72ce2f75b236588602985adb79bb72ddb5b3cba3";

  goPackagePath = "github.com/msprev/fzf-bibtex";
  subPackages = [ "cmd/bibtex-ls" "cmd/bibtex-cite" "cmd/bibtex-markdown" ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/msprev/fzf-bibtex";
    sha256 = "14k0dyq3pppwa4dqfn95dn35mxz7frg71a259xirs6qi20mchcjj";
  };

  goDeps = ./deps.nix;

  outputs = [ "bin" "out" ];

  meta = {
      description = "Tool to query a bibtex database using FZF";
      homepage    = "https://github.com/msprev/fzf-bibtex";
      maintainers = with stdenv.lib.maintainers; [ lucas8 ];
      license     = stdenv.lib.licenses.bsd3;
      platforms   = with stdenv.lib.platforms; linux;
  };
}
