import XMonad hiding ((|||))
import XMonad.Layout hiding ((|||))
import XMonad.Operations
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.ManageDocks
import XMonad.Hooks.ManageHelpers
import XMonad.Hooks.EwmhDesktops
import XMonad.Actions.CycleWS
import XMonad.Actions.Volume
import XMonad.Layout.Spacing
import qualified XMonad.StackSet as W
import XMonad.Util.Run (spawnPipe)
import XMonad.Util.EZConfig (additionalKeys)
import XMonad.Util.NamedWindows (getName)
import System.IO
import System.Exit
import qualified Data.Map as M
import Graphics.X11.ExtraTypes.XF86

import XMonad.Layout.Accordion
import XMonad.Layout.AutoMaster
import XMonad.Layout.CenteredMaster
import XMonad.Layout.Grid
import XMonad.Layout.Circle
import XMonad.Layout.Combo
import XMonad.Layout.TwoPane
import XMonad.Layout.Cross
import XMonad.Layout.Drawer
import XMonad.Layout.MagicFocus -- Move focused window to master
import XMonad.Layout.Magnifier  -- Increase size of the focused window
import XMonad.Layout.Master
import XMonad.Layout.Mosaic
import XMonad.Layout.NoBorders -- noBorders transformer
import XMonad.Layout.OneBig
import XMonad.Layout.PerWorkspace -- Configure layouts on per-workspace basis
import XMonad.Layout.Roledex -- Better than circle
import XMonad.Layout.Spiral
import XMonad.Actions.RotSlaves
import XMonad.Layout.ToggleLayouts
import XMonad.Actions.Submap
import XMonad.Actions.TopicSpace -- An alternative to workspaces
import XMonad.Actions.UpdatePointer
import XMonad.Layout.Column
import XMonad.Layout.LayoutCombinators
import XMonad.Layout.Renamed

-- File generated by home-manager, with relevant information
import qualified Nix

-- Interesting layouts :
--  - Circle
--  - mastered (1/100) 0.6 Accordion
--  - Roledex
--  - spiral (6/7)

modkey = mod4Mask

mlayout = Full ||| tiled ||| Circle
 where tiled   = renamed [Replace "Tiled"] inter
       inter   = spacingRaw False (mkBord 0) False (mkBord 10) True
               $ mastered delta ratio $ toggleLayouts Accordion $ Column 1
       ratio   = 0.5 -- Change to golden ratio
       delta   = 3/100
       mkBord  = \n -> Border n n n n

mworkspaces = ["r1", "l1", "l4", "l3", "l2", "music", "misc", "r2", "r3", "r4"]
wkkeys = [xK_j, xK_f, xK_q, xK_s, xK_d, xK_g, xK_h, xK_k, xK_l, xK_m]

rofi_calc = Nix.calculator

keybinds = M.fromList $ foldl kwk
         [ ((modkey .|. shiftMask, xK_n),  io (exitWith ExitSuccess))
         -- Client focus control
         , ((modkey, xK_x),                         kill)
         , ((modkey, xK_Tab),                       windows W.focusDown)
         , ((modkey .|. shiftMask, xK_Tab),         rotSlavesDown)
         , ((modkey, xK_twosuperior),               windows W.focusUp)
         , ((modkey .|. shiftMask, xK_twosuperior), rotSlavesUp)
         , ((modkey, xK_i),                         windows W.focusDown)
         , ((modkey, xK_o),                         windows W.focusUp)
         , ((modkey .|. shiftMask, xK_Return),      windows W.swapMaster)
         , ((modkey, xK_space),                     windows W.focusMaster)
         -- Screen focus control
         , ((modkey, xK_comma),                   prevScreen)
         , ((modkey, xK_semicolon),               nextScreen)
         , ((modkey .|. shiftMask, xK_comma),     shiftPrevScreen)
         , ((modkey .|. shiftMask, xK_semicolon), shiftNextScreen)
         , ((modkey .|. shiftMask, xK_o),         shiftNextScreen >> nextScreen)
         -- Layout control
         , ((modkey, xK_a), sendMessage $ JumpToLayout "Full")
         , ((modkey .|. shiftMask, xK_z), sendMessage ToggleLayout)
         , ((modkey, xK_z), sendMessage $ JumpToLayout "Tiled")
         , ((modkey, xK_e), sendMessage $ JumpToLayout "Circle")
         -- TODO Media players control
         ] $ zip mworkspaces wkkeys
 where kwk l (wk,k) = l ++
         [ ((modkey, k),               windows $ W.greedyView wk)
         , ((modkey .|. shiftMask, k), windows $ W.shift wk)]

loghk xmp = dynamicLogWithPP xmobarPP
          { ppOutput  = hPutStrLn xmp
          , ppTitle   = xmobarColor "#d7c8bc" "" . shorten 100
          , ppLayout  = const "" -- to disable layout info on xmobar
          , ppSep     = " | "
          , ppCurrent = xmobarColor "#ca7f32" ""
          , ppVisible = xmobarColor "#e0ac16" ""
          , ppHidden  = xmobarColor "#d7c8bc" ""
          }

myManageHook = composeAll
    [ title =? "Property Browser — SolveSpace" --> doFloat
    , className =? "popup" --> doRectFloat (W.RationalRect 0.1 0.1 0.8 0.8)
    --, role =? "GtkFileChooserDialog" --> doFloat -- role is not defined
    ]

mconfig xmp1 = ewmh $ docks $ def
        { borderWidth        = 2
        , terminal           = Nix.terminal
        , normalBorderColor  = "#b4a490"
        , focusedBorderColor = "#6eb958"
        , modMask            = modkey
        , layoutHook         = avoidStruts $ mlayout
        , workspaces         = mworkspaces
        , keys               = const keybinds
        , manageHook         = manageDocks <+> myManageHook <+> manageHook def
        , logHook            = loghk xmp1 >> updatePointer (0.5,0.5) (0,0)
        , handleEventHook    = handleEventHook def <+> fullscreenEventHook
        }

main = do xmp1 <- spawnPipe Nix.xmobarCmd
          xmonad $ mconfig xmp1
